DROP DATABASE IF EXISTS OrangeGrooveStreet;
CREATE DATABASE OrangeGrooveStreet;
USE OrangeGrooveStreet;

DROP TABLE IF EXISTS Usuario;
CREATE TABLE Usuario(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    usuario VARCHAR(32) NOT NULL,
    senha CHAR(32) NOT NULL
)ENGINE=InnoDB;

DROP TABLE IF EXISTS Funcionario;
CREATE TABLE Funcionario(
    rf INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome VARCHAR(32) NOT NULL,
    cargo VARCHAR(32) NOT NULL,
    cpf CHAR(11) NOT NULL,
    stat INT NOT NULL
)ENGINE=InnoDB;